version: '2'

services:
  python:
    image: $IMAGE:$TAG
    ports:
      - 50051:50051
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myproject
      - POSTGRES_HOST=postgres
