// Code generated by protoc-gen-go. DO NOT EDIT.
// source: face_rec.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error int32

const (
	Error_NoFaces          Error = 0
	Error_MoreThanOneFace  Error = 1
	Error_UnautherizedFace Error = 2
)

var Error_name = map[int32]string{
	0: "NoFaces",
	1: "MoreThanOneFace",
	2: "UnautherizedFace",
}

var Error_value = map[string]int32{
	"NoFaces":          0,
	"MoreThanOneFace":  1,
	"UnautherizedFace": 2,
}

func (x Error) String() string {
	return proto.EnumName(Error_name, int32(x))
}

func (Error) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9878e51acdf3bd58, []int{0}
}

type Response struct {
	Value                float32  `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9878e51acdf3bd58, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	UserName             string   `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	ProfilePhoto         string   `protobuf:"bytes,5,opt,name=profile_photo,json=profilePhoto,proto3" json:"profile_photo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_9878e51acdf3bd58, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetProfilePhoto() string {
	if m != nil {
		return m.ProfilePhoto
	}
	return ""
}

type AuthenticatedResponse struct {
	Authenticated        bool     `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	Message              Error    `protobuf:"varint,2,opt,name=message,proto3,enum=v1.Error" json:"message,omitempty"`
	ErrorCode            string   `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticatedResponse) Reset()         { *m = AuthenticatedResponse{} }
func (m *AuthenticatedResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticatedResponse) ProtoMessage()    {}
func (*AuthenticatedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9878e51acdf3bd58, []int{2}
}

func (m *AuthenticatedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticatedResponse.Unmarshal(m, b)
}
func (m *AuthenticatedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticatedResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticatedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticatedResponse.Merge(m, src)
}
func (m *AuthenticatedResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticatedResponse.Size(m)
}
func (m *AuthenticatedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticatedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticatedResponse proto.InternalMessageInfo

func (m *AuthenticatedResponse) GetAuthenticated() bool {
	if m != nil {
		return m.Authenticated
	}
	return false
}

func (m *AuthenticatedResponse) GetMessage() Error {
	if m != nil {
		return m.Message
	}
	return Error_NoFaces
}

func (m *AuthenticatedResponse) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

type ValidateRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Face                 string   `protobuf:"bytes,2,opt,name=face,proto3" json:"face,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateRequest) Reset()         { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()    {}
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9878e51acdf3bd58, []int{3}
}

func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}
func (m *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(m, src)
}
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

func (m *ValidateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ValidateRequest) GetFace() string {
	if m != nil {
		return m.Face
	}
	return ""
}

type ValidateResponse struct {
	Api                  string                 `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Authenticated        *AuthenticatedResponse `protobuf:"bytes,2,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	User                 *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ValidateResponse) Reset()         { *m = ValidateResponse{} }
func (m *ValidateResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateResponse) ProtoMessage()    {}
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9878e51acdf3bd58, []int{4}
}

func (m *ValidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateResponse.Unmarshal(m, b)
}
func (m *ValidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateResponse.Marshal(b, m, deterministic)
}
func (m *ValidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateResponse.Merge(m, src)
}
func (m *ValidateResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateResponse.Size(m)
}
func (m *ValidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateResponse proto.InternalMessageInfo

func (m *ValidateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ValidateResponse) GetAuthenticated() *AuthenticatedResponse {
	if m != nil {
		return m.Authenticated
	}
	return nil
}

func (m *ValidateResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterEnum("v1.Error", Error_name, Error_value)
	proto.RegisterType((*Response)(nil), "v1.Response")
	proto.RegisterType((*User)(nil), "v1.User")
	proto.RegisterType((*AuthenticatedResponse)(nil), "v1.AuthenticatedResponse")
	proto.RegisterType((*ValidateRequest)(nil), "v1.ValidateRequest")
	proto.RegisterType((*ValidateResponse)(nil), "v1.ValidateResponse")
}

func init() { proto.RegisterFile("face_rec.proto", fileDescriptor_9878e51acdf3bd58) }

var fileDescriptor_9878e51acdf3bd58 = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0xce, 0xd2, 0x40,
	0x14, 0xc5, 0x6d, 0x29, 0xd2, 0x5e, 0xfc, 0xf8, 0x9a, 0x01, 0x13, 0xfc, 0x97, 0x90, 0xe2, 0x82,
	0xb8, 0x20, 0xa1, 0x2e, 0x5c, 0x19, 0x62, 0x8c, 0xc6, 0x8d, 0x68, 0x26, 0xe2, 0xb6, 0x19, 0xdb,
	0x8b, 0x4c, 0x52, 0x3a, 0x75, 0x66, 0xca, 0xc2, 0x9d, 0xf1, 0x15, 0x7c, 0x60, 0x73, 0xa7, 0x54,
	0x01, 0xdd, 0xdd, 0xfe, 0x4e, 0xef, 0xcc, 0x39, 0xa7, 0x85, 0xd1, 0x4e, 0xe4, 0x98, 0x69, 0xcc,
	0x97, 0xb5, 0x56, 0x56, 0x31, 0xff, 0xb8, 0x4a, 0x66, 0x10, 0x72, 0x34, 0xb5, 0xaa, 0x0c, 0xb2,
	0x09, 0xf4, 0x8f, 0xa2, 0x6c, 0x70, 0xea, 0xcd, 0xbc, 0x85, 0xcf, 0xdb, 0x87, 0xe4, 0x97, 0x07,
	0xc1, 0xd6, 0xa0, 0x66, 0x23, 0xf0, 0x65, 0xe1, 0xb4, 0x1e, 0xf7, 0x65, 0xc1, 0x9e, 0x00, 0xec,
	0xa4, 0x36, 0x36, 0xab, 0xc4, 0x01, 0xa7, 0xfe, 0xcc, 0x5b, 0x44, 0x3c, 0x72, 0x64, 0x23, 0x0e,
	0xc8, 0x1e, 0x41, 0x54, 0x8a, 0x4e, 0xed, 0x39, 0x35, 0x24, 0xd0, 0x89, 0x8d, 0x41, 0xdd, 0x8a,
	0x41, 0x2b, 0x12, 0x70, 0xe2, 0x1c, 0x6e, 0x6a, 0xad, 0x76, 0xb2, 0xc4, 0xac, 0xde, 0x2b, 0xab,
	0xa6, 0x7d, 0xf7, 0xc2, 0xbd, 0x13, 0xfc, 0x48, 0x2c, 0xf9, 0xe1, 0xc1, 0xfd, 0x57, 0x8d, 0xdd,
	0x63, 0x65, 0x65, 0x2e, 0x2c, 0x16, 0x7f, 0x62, 0x3c, 0x85, 0x1b, 0x71, 0x2e, 0x38, 0xcb, 0x21,
	0xbf, 0x84, 0x6c, 0x0e, 0x83, 0x03, 0x1a, 0x23, 0xbe, 0xb6, 0xd6, 0x47, 0x69, 0xb4, 0x3c, 0xae,
	0x96, 0x6f, 0xb4, 0x56, 0x9a, 0x77, 0x0a, 0x45, 0x44, 0x22, 0x59, 0xae, 0x8a, 0x2e, 0x44, 0xe4,
	0xc8, 0x6b, 0x55, 0x60, 0xf2, 0x02, 0x6e, 0x3f, 0x8b, 0x52, 0x16, 0xc2, 0x22, 0xc7, 0x6f, 0x0d,
	0x1a, 0xcb, 0x62, 0xe8, 0x89, 0x5a, 0xba, 0x2b, 0x23, 0x4e, 0x23, 0x63, 0x10, 0x50, 0xef, 0xa7,
	0x82, 0xdc, 0x9c, 0xfc, 0xf4, 0x20, 0xfe, 0xbb, 0x79, 0xf2, 0xfd, 0xef, 0xea, 0xfa, 0x3a, 0x09,
	0x9d, 0x31, 0x4c, 0x1f, 0x90, 0xd3, 0xff, 0x66, 0xbf, 0x0e, 0xf9, 0x18, 0x02, 0x6a, 0xd5, 0x39,
	0x1f, 0xa6, 0x21, 0xed, 0xd1, 0xa7, 0xe4, 0x8e, 0x3e, 0x5b, 0x43, 0xdf, 0xe5, 0x65, 0x43, 0x18,
	0x6c, 0xd4, 0x5b, 0x91, 0xa3, 0x89, 0xef, 0xb0, 0x31, 0xdc, 0xbe, 0x57, 0x1a, 0x3f, 0xed, 0x45,
	0xf5, 0xa1, 0x42, 0xa2, 0xb1, 0xc7, 0x26, 0x10, 0x6f, 0x2b, 0x77, 0xb6, 0x96, 0xdf, 0xb1, 0x70,
	0xd4, 0x4f, 0xdf, 0xc1, 0x80, 0x26, 0x8e, 0x39, 0x7b, 0x09, 0xf1, 0xb9, 0x23, 0xc2, 0x6c, 0x4c,
	0xf7, 0x5d, 0x15, 0xf4, 0x70, 0x72, 0x09, 0x5b, 0xdf, 0x5f, 0xee, 0xba, 0x3f, 0xf2, 0xf9, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x2e, 0xa0, 0x2e, 0xbb, 0xa3, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FaceRecClient is the client API for FaceRec service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FaceRecClient interface {
	AuthenticateFace(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
}

type faceRecClient struct {
	cc *grpc.ClientConn
}

func NewFaceRecClient(cc *grpc.ClientConn) FaceRecClient {
	return &faceRecClient{cc}
}

func (c *faceRecClient) AuthenticateFace(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, "/v1.FaceRec/AuthenticateFace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaceRecServer is the server API for FaceRec service.
type FaceRecServer interface {
	AuthenticateFace(context.Context, *ValidateRequest) (*ValidateResponse, error)
}

func RegisterFaceRecServer(s *grpc.Server, srv FaceRecServer) {
	s.RegisterService(&_FaceRec_serviceDesc, srv)
}

func _FaceRec_AuthenticateFace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceRecServer).AuthenticateFace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.FaceRec/AuthenticateFace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceRecServer).AuthenticateFace(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FaceRec_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.FaceRec",
	HandlerType: (*FaceRecServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthenticateFace",
			Handler:    _FaceRec_AuthenticateFace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "face_rec.proto",
}
