# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import face_rec_pb2 as face__rec__pb2


class FaceRecStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AuthenticateFace = channel.unary_unary(
        '/v1.FaceRec/AuthenticateFace',
        request_serializer=face__rec__pb2.ValidateRequest.SerializeToString,
        response_deserializer=face__rec__pb2.ValidateResponse.FromString,
        )


class FaceRecServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AuthenticateFace(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FaceRecServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AuthenticateFace': grpc.unary_unary_rpc_method_handler(
          servicer.AuthenticateFace,
          request_deserializer=face__rec__pb2.ValidateRequest.FromString,
          response_serializer=face__rec__pb2.ValidateResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'v1.FaceRec', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
