# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face_rec.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='face_rec.proto',
  package='v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x66\x61\x63\x65_rec.proto\x12\x02v1\"\x19\n\x08Response\x12\r\n\x05value\x18\x01 \x01(\x02\"c\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x11\n\tuser_name\x18\x04 \x01(\t\x12\x15\n\rprofile_photo\x18\x05 \x01(\t\"^\n\x15\x41uthenticatedResponse\x12\x15\n\rauthenticated\x18\x01 \x01(\x08\x12\x1a\n\x07message\x18\x02 \x01(\x0e\x32\t.v1.Error\x12\x12\n\nerror_code\x18\x03 \x01(\t\",\n\x0fValidateRequest\x12\x0b\n\x03\x61pi\x18\x01 \x01(\t\x12\x0c\n\x04\x66\x61\x63\x65\x18\x02 \x01(\t\"i\n\x10ValidateResponse\x12\x0b\n\x03\x61pi\x18\x01 \x01(\t\x12\x30\n\rauthenticated\x18\x02 \x01(\x0b\x32\x19.v1.AuthenticatedResponse\x12\x16\n\x04user\x18\x03 \x01(\x0b\x32\x08.v1.User*?\n\x05\x45rror\x12\x0b\n\x07NoFaces\x10\x00\x12\x13\n\x0fMoreThanOneFace\x10\x01\x12\x14\n\x10UnautherizedFace\x10\x02\x32H\n\x07\x46\x61\x63\x65Rec\x12=\n\x10\x41uthenticateFace\x12\x13.v1.ValidateRequest\x1a\x14.v1.ValidateResponseb\x06proto3')
)

_ERROR = _descriptor.EnumDescriptor(
  name='Error',
  full_name='v1.Error',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NoFaces', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MoreThanOneFace', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UnautherizedFace', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=399,
  serialized_end=462,
)
_sym_db.RegisterEnumDescriptor(_ERROR)

Error = enum_type_wrapper.EnumTypeWrapper(_ERROR)
NoFaces = 0
MoreThanOneFace = 1
UnautherizedFace = 2



_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='v1.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='v1.Response.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=47,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='v1.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='v1.User.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='v1.User.first_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='v1.User.last_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_name', full_name='v1.User.user_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profile_photo', full_name='v1.User.profile_photo', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=148,
)


_AUTHENTICATEDRESPONSE = _descriptor.Descriptor(
  name='AuthenticatedResponse',
  full_name='v1.AuthenticatedResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='authenticated', full_name='v1.AuthenticatedResponse.authenticated', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='v1.AuthenticatedResponse.message', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='v1.AuthenticatedResponse.error_code', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=244,
)


_VALIDATEREQUEST = _descriptor.Descriptor(
  name='ValidateRequest',
  full_name='v1.ValidateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='api', full_name='v1.ValidateRequest.api', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face', full_name='v1.ValidateRequest.face', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=290,
)


_VALIDATERESPONSE = _descriptor.Descriptor(
  name='ValidateResponse',
  full_name='v1.ValidateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='api', full_name='v1.ValidateResponse.api', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authenticated', full_name='v1.ValidateResponse.authenticated', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='v1.ValidateResponse.user', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=397,
)

_AUTHENTICATEDRESPONSE.fields_by_name['message'].enum_type = _ERROR
_VALIDATERESPONSE.fields_by_name['authenticated'].message_type = _AUTHENTICATEDRESPONSE
_VALIDATERESPONSE.fields_by_name['user'].message_type = _USER
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['AuthenticatedResponse'] = _AUTHENTICATEDRESPONSE
DESCRIPTOR.message_types_by_name['ValidateRequest'] = _VALIDATEREQUEST
DESCRIPTOR.message_types_by_name['ValidateResponse'] = _VALIDATERESPONSE
DESCRIPTOR.enum_types_by_name['Error'] = _ERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'face_rec_pb2'
  # @@protoc_insertion_point(class_scope:v1.Response)
  ))
_sym_db.RegisterMessage(Response)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'face_rec_pb2'
  # @@protoc_insertion_point(class_scope:v1.User)
  ))
_sym_db.RegisterMessage(User)

AuthenticatedResponse = _reflection.GeneratedProtocolMessageType('AuthenticatedResponse', (_message.Message,), dict(
  DESCRIPTOR = _AUTHENTICATEDRESPONSE,
  __module__ = 'face_rec_pb2'
  # @@protoc_insertion_point(class_scope:v1.AuthenticatedResponse)
  ))
_sym_db.RegisterMessage(AuthenticatedResponse)

ValidateRequest = _reflection.GeneratedProtocolMessageType('ValidateRequest', (_message.Message,), dict(
  DESCRIPTOR = _VALIDATEREQUEST,
  __module__ = 'face_rec_pb2'
  # @@protoc_insertion_point(class_scope:v1.ValidateRequest)
  ))
_sym_db.RegisterMessage(ValidateRequest)

ValidateResponse = _reflection.GeneratedProtocolMessageType('ValidateResponse', (_message.Message,), dict(
  DESCRIPTOR = _VALIDATERESPONSE,
  __module__ = 'face_rec_pb2'
  # @@protoc_insertion_point(class_scope:v1.ValidateResponse)
  ))
_sym_db.RegisterMessage(ValidateResponse)



_FACEREC = _descriptor.ServiceDescriptor(
  name='FaceRec',
  full_name='v1.FaceRec',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=464,
  serialized_end=536,
  methods=[
  _descriptor.MethodDescriptor(
    name='AuthenticateFace',
    full_name='v1.FaceRec.AuthenticateFace',
    index=0,
    containing_service=None,
    input_type=_VALIDATEREQUEST,
    output_type=_VALIDATERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACEREC)

DESCRIPTOR.services_by_name['FaceRec'] = _FACEREC

# @@protoc_insertion_point(module_scope)
